profile_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userprofile.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from django.contrib.auth import views as authentication_views

from userprofile import views
from userprofile.forms import CustomAuthentication

app_name = 'uprofile'

urlpatterns = [
    # path('admin/', admin.site.urls),
    # path('user/', include('userprofile.urls'))
    path('register/', views.register, name="register"),
    path('login/', authentication_views.LoginView.as_view(form_class=CustomAuthentication,template_name='userprofile/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='userprofile/logout.html'), name='logout'),
    path('home/', views.home, name = 'home'),
    path('userdetails/<int:empid>', views.user_details, name = 'usrdetails'),
    path('delete_profile/<int:empid>', views.delete_profile, name = 'deleteprofile'),
    path('export_profile/<int:empid>', views.export_profile, name = 'exportprofile'),
    path('export_all_profile/', views.export_all_profile, name = 'exportallprofile'),
    path('add_users/', views.add_users, name = 'addusers'),
    path('sample_csv/', views.sample_csv, name = 'samplecsv'),
    path('oauth2callback/', views.oauth2callback, name = 'oauth2callback'),
    path('email/', views.email_tab, name='emailtab'),
    path('list_inbox_emails/', views.list_inbox_emails, name='list_inbox_emails'),
    path('open_email/<str:id>', views.open_email, name='openemail'),
    path('reply/<str:id>', views.reply_to_email, name='replytoemail'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

gender_choices = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other')
]
desi_choices = [
    ('IT', 'Information Technology'),
    ('S', 'Sales'),
    ('CS', 'Customer service'),        
]

class UserProfile(AbstractUser):
    """Custom users table"""
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    username = None
    first_name = None
    last_name = None
    dob = models.DateField()
    doj = models.DateField()
    gender = models.CharField(max_length=10, choices=gender_choices)
    designation = models.CharField(max_length=50, choices=desi_choices)
    manager = models.CharField(max_length=255, blank=True, null=True)
    pic = models.ImageField(upload_to='userprofile/images', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

userprofile/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from userprofile.models import UserProfile


class RegisterForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ['email', 'name', 'dob', 'doj', 'gender', 'designation', 'manager', 'pic', 'password']
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),
            'doj': forms.DateInput(attrs={'type': 'date'}),
            'pic': forms.FileInput(attrs={'class': 'form-control py-2', 'type': 'file', 'id': 'formFile'}),
            'password': forms.PasswordInput(),
            'gender': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            'designation': forms.Select(attrs={'class': 'form-select form-select-sm'}),
        }
    
    def save(self):
        data = self.cleaned_data
        password = data.pop('password', None)
        user = UserProfile(**data)
        user.set_password(password)
        user.save()
        return user


class CustomAuthentication(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'name': 'email', 'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password', 'name': 'password', 'placeholder': 'Password'}))


class UserDetailsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['id', 'name', 'dob', 'doj', 'gender', 'designation', 'manager', 'pic']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'dob': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'doj': forms.DateInput(attrs={'type': 'date','class': 'form-control'}),
            'pic': forms.FileInput(attrs={'class': 'form-control py-2', 'type': 'file', 'id': 'formFile'}),
            'gender': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            'designation': forms.Select(attrs={'class': 'form-select form-select-sm'}),
            'manager':forms.TextInput(attrs={'class': 'form-control'}),
        }

userprofile/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Q
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.urls import reverse

from userprofile.forms import RegisterForm, UserDetailsForm
from userprofile.models import UserProfile, gender_choices, desi_choices

import csv, os, io, json, base64
from datetime import datetime

# from google.auth.transport.requests import Request
# from google.oauth2.credentials import Credentials
# from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from oauth2client.client import OAuth2WebServerFlow, FlowExchangeError
from google.oauth2.credentials import Credentials
# from googleapiclient.discovery import build


def register(request):
    if request.method == 'POST':
        print(request.FILES)
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # email = form.cleaned_data.get('email')
            name = form.cleaned_data.get('name')
            messages.success(request, f"Welcome {name}, your account is created!")
            return redirect('uprofile:login')
    else:
        form = RegisterForm()

    return render(request, 'userprofile/register.html', {'form': form})


@login_required(login_url='uprofile:login')
def home(request):
    search_value = request.GET.get('search')
    print(search_value)
    if not search_value:
        user = UserProfile.objects.all().values_list('id','name', 'designation', 'gender', 'dob', 'doj', 'manager')
    else:
        print('here')
        user = UserProfile.objects.filter(Q(name__icontains=search_value) | Q(email__icontains=search_value) | Q(designation__icontains=search_value) | Q(manager__icontains=search_value)).values_list('id','name', 'designation', 'gender', 'dob', 'doj', 'manager')
        print(user)
    return render(request, 'userprofile/home.html', {'user_list': user, 'gender_choices': dict(gender_choices), 'desig_choices': dict(desi_choices)})


@login_required(login_url='uprofile:login')
def user_details(request, empid):
    emp = UserProfile.objects.filter(id=empid).first()
    print(emp.id)
    if request.method == 'POST':
        print('here')
        form = UserDetailsForm(request.POST, request.FILES, instance=emp)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect('uprofile:home')
        else:
            print(form.errors)
    else:
        # emp = UserProfile.objects.filter(id=empid).first()
        form = UserDetailsForm(instance=emp)
    
    # service = authenticate_gmail_api(request)

    # results = service.users().messages().list(userId='me', labelIds=['INBOX']).execute()
    # messages = results.get('messages', [])

    # email_data = []

    # if messages:
    #     for message in messages:
    #         msg = service.users().messages().get(userId='me', id=message['id']).execute()
    #         subject = None
    #         for header in msg['payload']['headers']:
    #             if header['name'] == 'Subject':
    #                 subject = header['value']
    #                 break

    #         email_data.append({
    #             'id': message['id'],
    #             'subject': subject
    #         })

    return render(request, 'userprofile/user_details.html', {"form": form, 'instance': emp, 'is_pic': True if emp.pic else False})


@login_required(login_url='uprofile:login')
def delete_profile(request,empid):
    user = UserProfile.objects.filter(id=empid).first()
    user.delete()
    if request.user == user:
        return redirect('uprofile:login')
    return redirect('uprofile:home')


@login_required(login_url='uprofile:login')
def export_profile(request, empid):
    print(empid)
    user = UserProfile.objects.filter(id=empid).values('id', 'name', 'email', 'gender', 'dob', 'doj', 'designation', 'manager', 'last_login', 'is_active').first()
    print(user)
    if not user:
        messages.error(request, "Profile does not exist!")
        return redirect('uprofile:home')
    
    fields = list(user.keys())

    data = []
    data.append(user)
    print(data)

    filename = '_'.join(user['name'].split(' ')) + '_' + ''.join('_'.join(str(datetime.now(tz=settings.LOCAL_TIME_ZONE)).split(' ')).split('.')[0]).replace('-','_').replace(':','_') + '.csv'

    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(filename)

    # with open(filename, 'w') as csvfile:
    writer = csv.DictWriter(response,fieldnames=fields)
    writer.writeheader()
    writer.writerows(data)

    # messages.success(request, "Profile successfully downloaded!")
    return response


@login_required(login_url='uprofile:login')
def export_all_profile(request):
    user = UserProfile.objects.all().values('id', 'name', 'email', 'gender', 'dob', 'doj', 'designation', 'manager', 'last_login', 'is_active')
    if not len(user):
        messages.error(request, "No profile found!")
        return redirect('uprofile:home')
    
    fields = list(user[0].keys())
    print(fields)

    data = []
    for i in user:
        data.append(i)
    print(data)

    filename = 'all_profile_' + ''.join('_'.join(str(datetime.now(tz=settings.LOCAL_TIME_ZONE)).split(' ')).split('.')[0]).replace('-','_').replace(':','_') + '.csv'

    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(filename)

    # with open(filename, 'w') as csvfile:
    writer = csv.DictWriter(response,fieldnames=fields)
    writer.writeheader()
    writer.writerows(data)

    # messages.success(request, "Profile successfully downloaded!")
    return response


# def authenticate_gmail_api(request):
#     creds = None

#     if 'token' in request.session:
#         creds = Credentials.from_authorized_user_info(request.session['token'])

#     if not creds or not creds.valid:
#         flow = InstalledAppFlow.from_client_config(settings.GMAIL_API_CREDENTIALS, ['https://www.googleapis.com/auth/gmail.send'])
#         creds = flow.run_local_server(port=0)

#     request.session['token'] = creds.to_json()

#     service = build('gmail', 'v1', credentials=creds)
#     return service


@login_required(login_url='uprofile:login')
def add_users(request):
    if request.method == 'POST':
        try:
            file = request.FILES['inpt']
            decoded_file = file.read().decode('utf-8')
            io_string = io.StringIO(decoded_file)
            data = []
            keys = {}
            for i,j in enumerate(csv.reader(io_string, delimiter=',', quotechar='|')):
                dt = keys.copy()
                if i == 0:
                    for k in j:
                        keys[k] = None
                    continue
                for key,value in zip(dt.keys(),j):
                    if key == 'email' and (value == '' or value == None):
                        for a,b in keys.items():
                            keys[a] = None
                        break
                    dt[key]=value
                if dt['email'] == None:
                    continue
                data.append(dt)
            print(data)
            for user in data:
                password = user.pop('password')
                user = UserProfile(**user)
                user.set_password(password)
                user.save()
            messages.success(request, "Users Add Successfully!")
        except Exception as e:
            print('Exception----------', e)
    return render(request, 'userprofile/add_users.html', )


@login_required(login_url='uprofile:login')
def sample_csv(request):
    fields = ['name', 'email', 'designation', 'gender', 'doj', 'dob', 'manager', 'password']
    rows = [['', '', 'IT/S/CS', 'M/F/O', 'yyyy-mm-dd', 'yyyy-mm-dd', '']]
    response = HttpResponse(content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename('add_user.csv')
    writer = csv.writer(response)
    writer.writerow(fields)
    writer.writerows(rows)
    return response


flow = OAuth2WebServerFlow(
    client_id=settings.GOOGLE_OAUTH2_CLIENT_ID,
    client_secret=settings.GOOGLE_OAUTH2_CLIENT_SECRET,
    scope=['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send'],
    redirect_uri='http://localhost/user/oauth2callback',  # Should match your OAuth credentials
)

def oauth2callback(request):
    print('here')
    if 'code' not in request.GET:
        # The user denied access or something went wrong
        return HttpResponse('Access denied or error occurred.')

    try:
        # Exchange the authorization code for credentials
        credentials = flow.step2_exchange(request.GET['code'])
    except FlowExchangeError:
        return HttpResponse('Failed to exchange authorization code for credentials.')

    # Store the credentials in the Django session (you may want to use a database for production)
    request.session['credentials'] = credentials.to_json()

    # Redirect to a success page or display a message
    return HttpResponseRedirect(reverse('uprofile:list_inbox_emails'))


SCOPES = ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/gmail.send']

def list_inbox_emails(request):
    try:
        # Load stored credentials from the Django session
        credentials_info = request.session.get('credentials')
        credentials_dict = json.loads(credentials_info)
        print(credentials_dict)
        credentials = Credentials.from_authorized_user_info(credentials_dict, scopes=SCOPES)

        # Create a Gmail API service
        service = build('gmail', 'v1', credentials=credentials)

userprofile/templates/userprofile/add_users.html
{% extends 'userprofile/base.html' %}

{% block title %}
Add users
{% endblock %}

{% block body %}
<div class="container my-5">
    <div class="mb-3">
    <form method="POST" action="{% url 'uprofile:addusers' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="formFile" class="form-label mb-3">Upload csv to add multiple users! Need sample csv file <a href="{% url 'uprofile:samplecsv' %}">click here!</a></label>
        <input class="form-control" name="inpt" type="file" id="formFile">
        <input class="btn btn-success my-3 w-100" type="submit" value="Upload">
    </form>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <title>{% block title %} {% endblock %}</title>
    <style>{% block css %} {% endblock %}</style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'uprofile:home' %}">User Profile</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'uprofile:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/add_users">Add User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/email">Email</a>
                </li>
                </ul>
                <form class="d-flex" method="GET" action="{% url 'uprofile:home' %}">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" name="search" id="search" placeholder="name, email, manager, designation" aria-label="Search" value="{{request.GET.search}}">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    <a href="/user/logout" class="btn btn-outline-danger mx-3" type="button">Logout</a>
                </form>
            </div>
        </div>
    </nav>
    {%for message in messages%}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <p id = 'messages'>{{message}}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {%endfor%}
    {% block body %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- <script>
    $("#search").on("change", function () {
        var typedValue = $(this).val();

        $.ajax({
            url: '/user/home/',  // URL to the Django view
            method: 'GET',            // HTTP method (GET, POST, etc.)
            data: { value: typedValue },  // Data to send to the server
            success: function (data) {
                console.log(data)
            }
        });
    });
    </script> -->
  </body>
</html>

userprofile/templates/userprofile/email.html
{% extends 'userprofile/base.html' %}

{% block title %}
Email
{%endblock%}
{% block body %}
    
<div class="container my-5">
    {% for i in data %}
        <div class="list-group my-1">
            <a href="{% url 'uprofile:openemail' i.id %}" class="list-group-item list-group-item-action" aria-current="true">
            <div class="d-flex w-100 justify-content-between">
                <div class="w-60">
                    <h5 class="mb-1">Subject: {{i.subject}}</h5>
                </div>
                <small>{{i.date}}</small>
            </div>
            <p class="mb-1">{{i.content}}</p>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

userprofile/templates/userprofile/home.html
{% extends 'userprofile/base.html' %}


{% block body %}

<div class="container mt-5">
    <div class="d-flex align-items-end flex-column">
        <a href="{% url 'uprofile:exportallprofile' %}" class="w-100"><input class="btn btn-outline-success mb-2" type="button" value="Export All Profile"></a>
    </div>
    <ul class="list-group my-3">
        {% for i in user_list %}
        <form action="{% url 'uprofile:usrdetails' i.0 %}">
            {% csrf_token %}
            <button type="submit" class="list-group-item list-group-item-action py-4 my-1" id={{i.0}}>
            <!-- <li class="list-group-item py-4"> -->
                <div class="d-flex justify-content-between">
                    <div >Name: {{i.1}} </div>
                    <div>Designation: {% for key,value in desig_choices.items %}
                        {% if i.2 == key%}
                            {{value}}
                        {% endif %}
                        {% endfor %}</div>
                    </div>
                <div class="d-flex justify-content-between mt-4">
                    <div >Gender: {% for key,value in gender_choices.items %}
                        {% if i.3 == key%}
                            {{value}}
                        {% endif %}
                        {% endfor %} </div>
                    <div >Date of Birth: {{i.4}} </div>
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <div >Manager: {{i.6}} </div>
                    <div >Date of Joining: {{i.5}} </div>
                </div>
            </button>
        </form>
        {% endfor %}
    </ul>
</div>
{% endblock %}

userprofile/templates/userprofile/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <title>Login</title>
    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #8284df !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #5846bb;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #35cc2f !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 0rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>
  </head>
  <body>
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="px-1 py-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                                  </svg></i></span>
							</div>
							<!-- <input type="text" name="email" placeholder="Email" class="form-control" value = {{ username }}> -->
                            {{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="px-1 py-1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lock-fill" viewBox="0 0 16 16">
                                    <path d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
                                  </svg></i></span>
							</div>
							{{form.password}}
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {{form.errors}}
                {%for message in messages%}
                <p id = 'messages'>{{message}}</p>
                {%endfor%}

                <div class="mt-4">
					<div class="d-flex justify-content-center links" style="color: rgb(255, 255, 255);">
						Don't have an account?&nbsp; <a href="{% url 'uprofile:register' %}" class="ml-2" style="color: rgb(255, 255, 255); font-weight: bolder;"> Sign Up</a>
					</div>			
				</div>
		
			</div>
		</div>
	</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

userprofile/templates/userprofile/logout.html
<h3>You have successfully logout! To login please <a href="/user/login">click here</a></h3>

userprofile/templates/userprofile/open_email.html
{% extends 'userprofile/base.html' %}

{% block title %}
Opened email
{% endblock %}

{% block body %}
<div class="container my-5">
    <div class="mb-3">
        <div class="d-flex justify-content-between">
            <label for="exampleFormControlInput1" class="form-label fw-bold">From</label>
            <label for="exampleFormControlInput1" class="form-label ">{{email_data.date}}</label>
        </div>
        <input type="email" class="form-control" id="exampleFormControlInput1"  value="{{email_data.from}}" disabled>
    </div>
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label fw-bold">Subject</label>
        <input type="text" class="form-control" id="exampleFormControlInput1" value="{{email_data.subject}}" disabled>
    </div>
    <div class="mb-3">
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="12" disabled>{{email_data.content}}</textarea>
    </div>
    <div class="my-5">
        <form method="POST" action="{% url 'uprofile:replytoemail' email_data.id %}">
            {% csrf_token %}
            <input type="text" class="form-control" name="body" id="exampleFormControlInput2" placeholder="Reply here...">
            <button class="btn btn-outline-success w-25 my-3" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send" viewBox="0 0 16 16">
                <path d="M15.854.146a.5.5 0 0 1 .11.54l-5.819 14.547a.75.75 0 0 1-1.329.124l-3.178-4.995L.643 7.184a.75.75 0 0 1 .124-1.33L15.314.037a.5.5 0 0 1 .54.11ZM6.636 10.07l2.761 4.338L14.13 2.576 6.636 10.07Zm6.787-8.201L1.591 6.602l4.339 2.76 7.494-7.493Z"/>
            </svg> Send</button>
        </form>
    </div>
</div>
{% endblock %}

userprofile/templates/userprofile/user_details.html
{% extends 'userprofile/base.html' %}
{% block css %}
.login_btn {
    width: 48%;
    background: #35cc2f !important;
    color: white !important;
}
.login_btn:focus {
    box-shadow: none !important;
    outline: 0px !important;
}
.login_btn:hover {
    background: #198754 !important;
}
.delete_btn {
    width: 100%;
    color: white !important;
}
.delete_btn:focus {
    box-shadow: none !important;
    outline: 0px !important;
}
.exportbtn {
    width: 100%
}
{% endblock %}
{% block body %}
<div class="container d-flex justify-content-center my-5 ">
    <div class="d-inline-block">
        <div class="card" style="width: 16rem;">
            {% if is_pic %}
            <img src="{{instance.pic.url}}" class="rounded float-start" alt="{{instance.name}}">
            {% else %}
            <img src="" class="rounded float-start" alt="{{instance.name}}">
            {% endif %}
        </div>
    </div>
    <div class="d-inline-block mx-5">
        <a href="{% url 'uprofile:exportprofile' instance.id %}" class="w-100"><input class="btn btn-outline-success exportbtn mb-2" type="button" value="Export Profile"></a>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}          
            {{form.as_p}}
            <div class="d-flex justify-content-between">
                <input class="btn login_btn" type="submit" value="Update Profile">
                <a href="{% url 'uprofile:deleteprofile' instance.id %}" class="w-50"><input class="btn btn-danger delete_btn" type="button" value="Delete Profile"/></a>
            </div>
        </form>
    </div>
    <!-- {{emails}} -->
</div>
{% endblock %}